# -*- coding: utf-8 -*-
"""L2 - DadosFaltantes_Jean.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vju4BqihZFLhrkDzJFxhegz56yGe_k5T

Aluno: Jean Antonio Ribeiro<br>
RA: 265739
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
from google.colab import drive

drive.mount('/content/drive')

df_heart = pd.read_csv("/content/drive/My Drive/Colab Notebooks/home-master/data/heart/raw/heart.csv")
df_age   = pd.read_csv("/content/drive/My Drive/Colab Notebooks/home-master/data/heart/processed/heart-missing-age.csv")
df_chol  = pd.read_csv("/content/drive/My Drive/Colab Notebooks/home-master/data/heart/processed/heart-missing-chol.csv")
df_sex   = pd.read_csv("/content/drive/My Drive/Colab Notebooks/home-master/data/heart/processed/heart-missing-sex.csv")

df_heart.head()

"""# age

Classificação: MNAR, pois os dados faltantes podem ter sidos não informados ou importados de forma errada para a tabela, ocazionando falta de dados na tabela, por exemplo.

Descrição da solução proposta para reposição dos dados faltantes: pode-se aplicar a normalização dos dados e, em seguida, utilizar a média entre dois ou mais pontos.
"""

plt.figure()
plt.title('Gráfico de Dispersão Scatterplot de x1 x y1')
plt.xlabel('x1')
plt.ylabel('y1')
plt.scatter(range(0,len(df_heart['age'])),df_heart['age'])
plt.scatter(range(0,len(df_age['age'])),df_age['age'])
plt.grid()
plt.show()

plt.figure()
plt.title('Gráfico de Dispersão Scatterplot de x1 x y1')
plt.xlabel('x1')
plt.ylabel('y1')
plt.scatter(df_heart['age'], df_age['age'], c='k')
plt.grid()
plt.show()

plt.figure()
plt.title('Plot x1 x y1')
plt.xlabel('x1')
plt.ylabel('y1')
plt.plot(df_heart['age'], label='heart')
plt.plot(df_age['age'], label='age')
plt.grid()
plt.show()

df_age['age'].head(20)

"""# chol

Classificação: MNAR, pois os dados faltantes podem ter ocorridos por causa do aparelho que mede o colesterol ter falhado, por exemplo.

Descrição da solução proposta para reposição dos dados faltantes: pode-se utilizar a média entre dois ou mais pontos.
"""

plt.figure()
plt.title('Gráfico de Dispersão Scatterplot de x1 x y1')
plt.xlabel('x1')
plt.ylabel('y1')
plt.scatter(range(0,len(df_heart['chol'])),df_heart['chol'])
plt.scatter(range(0,len(df_chol['chol'])),df_chol['chol'])
plt.grid()
plt.show()

plt.figure()
plt.title('Gráfico de Dispersão Scatterplot de x1 x y1')
plt.xlabel('x1')
plt.ylabel('y1')
plt.scatter(df_heart['chol'], df_chol['chol'], c='k')
plt.grid()
plt.show()

plt.figure()
plt.title('Plot x1 x y1')
plt.xlabel('x1')
plt.ylabel('y1')
#plt.scatter(range(0,len(df_heart['chol'])),df_chol['chol'])
plt.plot(df_heart['chol'], label='heart')
plt.plot(df_chol['chol'], label='chol')
plt.grid()
plt.show()

df_chol['chol'].head(20)

"""# sex

Classificação: MAR, pois os dados faltantes podem ter sido não informados porque as pessoas não queriam ser identificados no requisito sexo, por exemplo.

Descrição da solução proposta para reposição dos dados faltantes: pode-se utilizar a distância entre dois pontos.
"""

plt.figure()
plt.title('Gráfico de Dispersão Scatterplot de x1 x y1')
plt.xlabel('x1')
plt.ylabel('y1')
plt.scatter(range(0,len(df_heart['sex'])),df_heart['sex'])
plt.scatter(range(0,len(df_sex['sex'])),df_sex['sex'])
plt.grid()
plt.show()

plt.figure()
plt.title('Gráfico de Dispersão Scatterplot de x1 x y1')
plt.xlabel('x1')
plt.ylabel('y1')
plt.scatter(df_heart['sex'], df_sex['sex'], c='k')
plt.grid()
plt.show()

plt.figure()
plt.title('Plot x1 x y1')
plt.xlabel('x1')
plt.ylabel('y1')
plt.plot(df_heart['sex'], label='heart')
plt.plot(df_sex['sex'], label='sex')
plt.ylim([min(plt.ylim()),max(plt.ylim())])
plt.grid()
plt.show()

df_sex['sex'].head(20)